recipe: default.v1
language: en
pipeline:
- name: NLUCommandAdapter
- name: MultiStepLLMCommandGenerator
  llm:
    model: "llama3.1"
    request_timeout: 10
    type: openai
    openai_api_base: http://localhost:11434/v1
    openai_api_key: foobar
  flow_retrieval:
    active: false
    embeddings:
      type: "huggingface"
      model_name: "sentence-transformers/all-mpnet-base-v2"
      task: "feature-extraction"
    

policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy
assistant_id: 20240907-033146-inverted-tenement
